### ISSUE TITLE
Question: How to get p-values 

### ISSUE THREAD

**Issue by Irazall** [mathijsdeen/ClusterBootstrap#17]
Thank you again for the useful package! Especially the fact of the parallel execution is very neat!

I wonder if it is possible to also extract p-values from the resulting object, similar to the clusterSEs package: https://www.rdocumentation.org/packages/clusterSEs/versions/2.6.5/topics/cluster.bs.glm

Until now, I only get the confidence intervals but I don't know how to translate this into p-values. I would need this to correct for multiple hypotheses testing. Or is there another way to adjust the resulting confidence intervals?

Thank you very much in advance!

**Comment by mathijsdeen** [comment]
Thanks for your kind words and apologies for the late response. 

The calculation of p-values is not possible (yet), though you could perhaps do a Z-test based on the bootstrap standard errors. Or perhaps do a one-sided test by calculating the percentage of bootstrap samples that is "on the opposite side" of your null-value (usually 0), looking from the estimate you found - doubling that percentage should resemble a two-sided test. The calculation of p-values is not very common in the application of the bootstrap, so I'd have to look into it before implementing it properly.
